### ISSUE TITLE
Installation through NuGet

### ISSUE THREAD

**Issue by mediumTaj** [mediumTaj/dot-net-sdk#11]
Make the SDK (and the base SDK submodule) available through NuGet.

**Comment by mediumTaj** [comment]
@atilatosta What do I need to do to be able to make this available through NuGet? Is it pretty straightforward?

**Comment by atilatosta** [comment]
@mediumTaj in the link below you have the step-by-step to create the package.

Https://docs.nuget.org/ndocs/quickstart/create-and-publish-a-package

If you need help I can create it for you.

**Comment by mediumTaj** [comment]
Published out first release `0.1.0` to NuGet under 

```
PM> Install-Package IBM.Watson
```
